### ISSUE TITLE
Karen Admin vs. Teacher Login

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#1]
Stella, I logged in under the admin user name and password and saw that Rob as a student passed chap 1 and 2 with 100% today. 
![image](https://user-images.githubusercontent.com/26387044/38272581-3fcc2c98-374f-11e8-9cee-2f81dc2515d3.png)

When i log into the SamTech Teacher login I created for myself, it doesnt show any score for Chap 1or 2 for Rob. You can see the 2 screens side by side above.

**Comment by SagarPC** [comment]
@kbt1 : We addressed this issue and now it's showing proper result for the leader. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/38306731-1a2e7320-382f-11e8-85db-c5273e19c140.png)

**Comment by kbt1** [comment]
looks good.
