### ISSUE TITLE
Wrong Exam Questions (Cylinder Head)

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#10]
The exam questions in chapter 17 "Preparing Performance Engines (Part B) are not the ones that were chosen.

I have attached the correct ones.
Thanks

[Chapter 17 Cylinder Head Test QuestionsTotal 25 (2).docx](https://github.com/stellaballa/AERAEDU/files/1877097/Chapter.17.Cylinder.Head.Test.QuestionsTotal.25.2.docx)

**Comment by SagarPC** [comment]
Updated newly provided question list on stage.

**Comment by robchar** [comment]
Done, thanks.
