### ISSUE TITLE
Chapter 14 Title Re-Name

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#11]
Please re-name Chapter 14 from "Resurfacing Cylinder Heads and Block" to

"Resurfacing Cylinder Heads"

Thanks

**Comment by SagarPC** [comment]
Updated name as suggested.

![image](https://user-images.githubusercontent.com/31076567/38361061-c02b3410-38e9-11e8-92cd-3f6f4c8bd33c.png)

**Comment by kbt1** [comment]
good to go
