### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#12]
On the CMS Lesson screen there is the drop down arrow to choose which account you want to view
- AERA Master School or Sem tech Internactional. (screen shot below)

Please change "Sem tech Internactional" to just "Sam Tech"
and also change Aera Master school to AERA Master School
Thanks

![image](https://user-images.githubusercontent.com/26470619/38373946-158671cc-38b8-11e8-85f0-ed48ece81f01.png)

**Comment by SagarPC** [comment]
We updated School name and uploaded on stage.

![image](https://user-images.githubusercontent.com/31076567/38424275-26a22b38-39ce-11e8-9f95-d1f8a08bfa84.png)

**Comment by robchar** [comment]
Done, thanks
