### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#13]
In the Test screen of the CMS under both AERA Master School and Sem tech Internactional there is a spelling error. Right now it is "Lessions" and it should be spelled "Lessons" (see screen shot below)

Thanks

![image](https://user-images.githubusercontent.com/26470619/38376223-bcbeef78-38bd-11e8-8a12-925f908d85fe.png)

**Comment by SagarPC** [comment]
We done with this correction.

![image](https://user-images.githubusercontent.com/31076567/38424229-f92e6798-39cd-11e8-8871-f17b0473d0cd.png)

**Comment by robchar** [comment]
Done, thanks
