### ISSUE TITLE
Exam questions are not in the same order as CMS

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#14]
The student Mid Term, Cylinder Block, and Cylinder Head Exam questions are in not in the same numbered order as the test questions on CMS. Please match both the CMS and student test questions the same.

Thanks

**Comment by SagarPC** [comment]
@robchar : Earlier we are shuffling question for Mid Term, Cylinder Block, and Cylinder Head Exam and because of that it's not in order. 

We remove that code so now it will show same order as we can see in CMS.

**Comment by robchar** [comment]
@SagarPC @aharmening @kbt1 @stellaballa Looks good, thanks.

Perhaps in several months after Sam Tech has been using the program for awhile we can put the code back in to have the questions shuffled, I just want to keep it simple for now.
