### ISSUE TITLE
Email notification of Cylinder Head and Cylinder Block Exam Completed

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#15]
Stella

Rob completed the Cylinder Block Exam and I did not receive email notification. 
Can you make sure that I am set up to receive email notification for Both the Cylinder Block Exam and Cylinder Head Exam completion.

Thank you

**Comment by stellaballa** [comment]
@SagarPC Notification email need to be sent to Karen:
Completion of Cylinder Block Exam
Completion of Block Exam
Completion of Midterm Exam
When teacher activate additional course for student.

**Comment by stellaballa** [comment]
@SagarPC 
The content for the email when teacher add course for the student should be:

Title: SamTech Added New Course for Student
Content: (Teacher Name) has added (Course Name) for (Student Name) on (Date).

**Comment by SagarPC** [comment]
@stellaballa : 

+++++++++++
When teacher activate additional course for student.
+++++++++++
above notification send to Karen or Student?

**Comment by stellaballa** [comment]
@SagarPC I guess it should be both. @kbt1 and @robchar ?

**Comment by kbt1** [comment]
Both would be good!

**Comment by SagarPC** [comment]
+++++++++
Completion of Cylinder Block Exam
Completion of Block Exam
Completion of Midterm Exam
+++++++++
_Subject: **(Stage)** A student has completed the course_

It will send notification to Karen only.


+++++++++
When teacher activate additional course for student.
+++++++++
_Subject: SamTech Added New Course for Student **(Stage)**_

It will send notification to Student and Karen both

I have added **(Stage)** to identify message from the stage not from live.

You can test this function on stage(test) website.

![image](https://user-images.githubusercontent.com/31076567/38425393-67e5c52a-39d1-11e8-9552-f8e22d9f05e1.png)

**Comment by kbt1** [comment]
good to go
