### ISSUE TITLE
Admin CMS

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#16]
Stella
In the Admin CMS, not sure what the "Export Data to Excel" button is for on the test page?

![image](https://user-images.githubusercontent.com/26387044/38388075-bf1900a2-38df-11e8-9431-687a921e6dce.png)

**Comment by stellaballa** [comment]
@SagarPC and it's not working. What is it exporting?

**Comment by SagarPC** [comment]
@stellaballa : It's exporting selected chapter question in csv. There is access issue on stage. I gave proper access and now it's working.

**Comment by kbt1** [comment]
nothing happens when i click on it.

**Comment by SagarPC** [comment]
@kbt1 : Please reload screen using Ctrl+F5 key and try again. I clicked and it working for me. There is few things related to browser cache so we need to reload page by pressing Ctrl+F5 key.

It's downloaded below file when I clicked on Export Data button.
http://stage.aeraedu.com/ClientBin/certReports/exam-1523092269.csv

**Comment by kbt1** [comment]
it works, looks good.
