### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#18]
Please change the two exam names in CMS in the Sam Tech screen from "Block Class" and "Head Class" to "Cylinder Block Exam" and "Cylinder Head Exam" (screen shot below) to stay consistent with the teacher screen.

Thanks

![image](https://user-images.githubusercontent.com/26470619/38427889-1473b4e8-3980-11e8-9ef3-15c5c1be18e9.png)

**Comment by SagarPC** [comment]
@robchar : We done with this change and uploaded on stage. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/38493030-607c66d8-3c0e-11e8-92c2-af221b5a7549.png)

**Comment by kbt1** [comment]
looks good
