### ISSUE TITLE
Notification Word Change

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#19]
Could we please change the format of the name and  date for notifications received.

This is how it is now: Munro Rob has added Cylinder Block Exam for Munro  on 2018/04/06.

can you make it "**Rob Munro** has added Cylinder Block Exam for Munro on **04/06/2018 MM/DD/YYYY.**

Thanks

**Comment by SagarPC** [comment]
Updated email content as suggested. Please verify our update.

**Comment by kbt1** [comment]
Still needs to be worded as is:

**The Instructor** has added Cylinder Head Exam for **Karen Tendering** on 04/09/18.

**Comment by SagarPC** [comment]
@kbt1 : now instructor and student both showing as bold font, is that okay or any change?

![image](https://user-images.githubusercontent.com/31076567/38551343-91045ee6-3cd6-11e8-9aa4-289201779e7b.png)

**Comment by kbt1** [comment]
This is how the wording needs to:  

"Group Leader First and Last Name" has added Cylinder Block Exam & Cylinder Head Exam for "Student First and Last name " on 04/10/18.

**Comment by SagarPC** [comment]
@kbt1 : Please see below image and let me know if any change in this.

![image](https://user-images.githubusercontent.com/31076567/38731955-fe44daac-3f39-11e8-9dae-d664e474ff76.png)

**Comment by kbt1** [comment]
This is still wrong, it needs to be first and last name, it is coming through as last and first name.

Group Leader Tendering Karen has added Cylinder Block Exam & Cylinder Head Exam for Tendering on 04/13/18. 

Should be: Group Leader **Karen Tendering** has added...........for **Karen Tendering** on 4/13/18.

**Comment by SagarPC** [comment]
@kbt1 : can you please check now?

![image](https://user-images.githubusercontent.com/31076567/38738145-f84b143a-3f4e-11e8-8997-2c6b7bfb8398.png)

**Comment by kbt1** [comment]
Perfect!
