### ISSUE TITLE
80% View wrong answers

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERAEDU#21]
If you get 80% you pass, but the wrong answer button appears. It doesn't work making it confusing. Can we remove this? so it's consistent with the other passed chapters. 
![image](https://user-images.githubusercontent.com/26386841/38515876-2ad13eb8-3bfb-11e8-859f-0627abdef138.png)

**Comment by SagarPC** [comment]
@aharmening: We removed that button when user passed the exam.

**Comment by amandagoyette** [comment]
Looks good. Thanks!
