### ISSUE TITLE
Cylinder Head Exam Question

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERAEDU#22]
Answers vary from Rob's Sheet to actual exam.
Exam:
![image](https://user-images.githubusercontent.com/26386841/38518828-a7c7342e-3c03-11e8-8685-0021290e1e3c.png)
Rob's Doc:
![image](https://user-images.githubusercontent.com/26386841/38518860-beabf7e2-3c03-11e8-931f-fdb7e293f7c7.png)

**Comment by SagarPC** [comment]
@aharmening : We looked int all file provided by Rob and notice there is issue with 1 more question. We resolved this issue for both question and now it's proper on stage.

**Comment by amandagoyette** [comment]
Thanks!
