### ISSUE TITLE
Completion email to Karen

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERAEDU#23]
Can we move the block exam so it appears under the block section so that the exam appears next to it's section for Karen:
![image](https://user-images.githubusercontent.com/26386841/38519914-de32fbf8-3c06-11e8-89fa-d6b259836fc3.png)

**Comment by SagarPC** [comment]
We done wit the order change in email.

![image](https://user-images.githubusercontent.com/31076567/38550874-469f17c0-3cd5-11e8-9681-9378973dbd85.png)

**Comment by kbt1** [comment]
good
