### ISSUE TITLE
Update format on date for Emails to Karen

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/AERAEDU#25]
Please change the format on the dates for the chapters from yyyy-mm-dd to mm-dd-yyyy  Thanks! 
![image](https://user-images.githubusercontent.com/26386841/38577278-140f149a-3cc6-11e8-9fba-e66a974e4c06.png)

**Comment by SagarPC** [comment]
We done with this change and uploaded on stage. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/38734262-85bcfc28-3f42-11e8-9947-40c6675c1f15.png)

**Comment by kbt1** [comment]
looks good.
