### ISSUE TITLE
CMS on Stage

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#26]
I have run this report "Export Date to Excel"  in the CMS side of Sam Tech and it worked.
Now I run the report and nothing happens

![image](https://user-images.githubusercontent.com/26387044/38701581-e19ef62a-3e63-11e8-9ac3-0e4ec176f83b.png)

**Comment by SagarPC** [comment]
@kbt1 : I found cause there is one specific case and in that case this export will stop working.

We fixed that things and uploaded change.

**Comment by kbt1** [comment]
works good now
