### ISSUE TITLE
SamTech Live

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#27]
I added Rob and myself both with a student login and group leader login.
![image](https://user-images.githubusercontent.com/26387044/39377095-9050590a-4a19-11e8-936e-9e69702bc755.png)

Everything looks good when I login under student.

When i login under group leader, nothing appears and i have refreshed my screen:
![image](https://user-images.githubusercontent.com/26387044/39377146-c927e4be-4a19-11e8-8064-b0eeb859342e.png)

**Comment by kbt1** [comment]
I used robs instructor login and the student list is there
i used mine, nothing is there.  karen2 and instructor2

**Comment by kbt1** [comment]
i created a 2nd leader login for myself and it works
test1 and test1 - not sure why this works and the other doesnt.

**Comment by kbt1** [comment]
i think i figured this out, the group leader must have both the cylinder head and cylinder block boxes checked.  am I correct on this?

**Comment by stellaballa** [comment]
@kbt1 not sure if that is the reason that trigger the account to work, but will look into it.

**Comment by kbt1** [comment]
i just edited Robs instructor login and when i unchecked one of the boxes and logged in, i couldnt see the students under his account either. I checked both boxes and the students are there.
Under Sam Tech, can we have both boxes automatically checked if the Group Leader box is checked?

**Comment by SagarPC** [comment]
@kbt1 : Group leader must have both exam selected. 

We added validation in user screen like Group Leader must have both exam selected automatically and admin not able to unchecked until "Group Leader" is checked. 

Please review update on live and let us know if any query.

![image](https://user-images.githubusercontent.com/31076567/39394060-ccd64728-4aea-11e8-93f8-44dc86918567.png)

**Comment by kbt1** [comment]
sounds good.
