### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/AERAEDU#28]
@SagarPC can we add a loading animation on the admin side, when the account page is loading? When I click on the pagination number the page goes blank for a few sec and then the content load.

**Comment by SagarPC** [comment]
@kbt1 : We have implemented loading animation on page change. Please refer below image and let me know if any change required in this update.

http://aeraedu.com/#/users

![image](https://user-images.githubusercontent.com/31076567/39470918-f265492e-4d5d-11e8-9bc1-f037c213c73a.png)

**Comment by kbt1** [comment]
i noticed that the system runs great now! i login, click on accounts and they are there. No more waiting for the page to load.  Great Job!!!!
