### ISSUE TITLE
Update #3 Notifications

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#29]
Hi Stella,

After the student completes the custom selected chapters and tests, are we going to get a notification to let us know when the student is all finished?

**Comment by stellaballa** [comment]
@robchar we didn't build out the notification system for individual classes to keep the project within budget.

**Comment by kbt1** [comment]
can there be notification when all the chapters selected are completed, not each individual one?
for example, somone signs up for chapters 1-5, when they are all passed, can i get notification?
If not, I can manually keep an eye on it. If this program takes off, maybe down the line we can look into notification.

**Comment by stellaballa** [comment]
@kbt1 let me discuss this with Sagar.

**Comment by SagarPC** [comment]
We done with this change and uploaded on stage.  Please confirm our update.

**Comment by kbt1** [comment]
It works perfectly!  thank you!
