### ISSUE TITLE
Stage Site Login for Update #3

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#30]
Hi Stella,

I am having trouble finding what login and password to use on the stage site, is it the same stage site link we have been using for update #2?

Thanks
Rob

**Comment by stellaballa** [comment]
@robchar correct. the URL is stage.aeraedu.com your login username is: munro

**Comment by kbt1** [comment]
Stella
Can you send me my login info also?

**Comment by stellaballa** [comment]
@kbt1 
UN: karen pw:5jiVsFo

**Comment by robchar** [comment]
Stella,

Could I also bug you for my password, thanks :)

**Comment by kbt1** [comment]
Stella, when i log into the stage site using that user name and password, this is what i see.
![image](https://user-images.githubusercontent.com/26387044/39839173-ee717092-53a0-11e8-9600-c92ac60fead4.png)
it looks like my login as a student not admin?

**Comment by SagarPC** [comment]
@stellaballa : I looked into this issue and notice there is update done under Administrator account and Admin converted to student.

We make code to prevent such update for Admin account also we hide all unwanted things for the Admin account to update. We can see screen like below when user comes to update Admin account form "Account" tab. This thinks prevent end-user to update anything for the Admin account as we are showing only those information which required for Admin

![image 2](https://user-images.githubusercontent.com/31076567/39870805-4951bc76-5480-11e8-892b-cf004738b907.png)

**Comment by kbt1** [comment]
that works.

can you correct spelling 
Account Type
 Studnet   Group  

should be Student

**Comment by kbt1** [comment]
Stella and Sagar
Can you test the notification of a student completion to Karen@aera.org
my email issue seems to be fixed so you can change it back to aera.org and remove my gmail account.

**Comment by SagarPC** [comment]
@kbt1 : I re-set email to karen@aera.org. please let me know if you start receiving email.

**Comment by kbt1** [comment]
When creating a new account, there is a spelling error
Account Type = Student   and  Group
Student is mispelled.

**Comment by robchar** [comment]
@stellaballa 
Hi Stella, I will need a login and password for the admin side to test as well. It looks like I am set up for the student side now.

Thanks
Rob

**Comment by anthonypartsconnect** [comment]
@robchar 

Hi Rob, 
We are working on getting you an admin account. In the meantime can you use Karen's admin acct? 
UN: karen PW:5jiVsFo

Thanks!  Let me know if you have any questions. 

Anthony

**Comment by robchar** [comment]
@anthonypartsconnect 

Hi Anthony,

Thanks.

**Comment by robchar** [comment]
@anthonypartsconnect 

Hi Anthony, The log in is working.
Thanks.

**Comment by anthonypartsconnect** [comment]
@robchar 
Great, please let me know if anything comes up.  
Anthony

**Comment by anthonypartsconnect** [comment]
Hi all, 

These have been generated for your team, please let me know if you have any questions. 

Stage: http://stage.aeraedu.com
Live: http://aeraedu.com

Username / Password
rob	/ rob@123#
karen / 5jiVsFo
Steve / qD6tdFR
amandapotter / aC9yfHP

Thank you!  
Anthony
