### ISSUE TITLE
Create ADMIN ACCT for AERA Users

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#31]
@SagarPC 
Can you please create admin accounts for all AERA users plus Stella and myself.

Rob, Karen, Steve, Amanda, Stella, Anthony 

Thank you!

Anthony

**Comment by SagarPC** [comment]
Please see below I create live/stage admin login as below. That will work for stage and live both.

Stage: http://stage.aeraedu.com
Live: http://aeraedu.com

Username / Password 
rob	/ rob@123#
karen / 5jiVsFo
Steve / qD6tdFR
amandapotter / aC9yfHP
stella / lai@123#
anthony / soto@123$

**Comment by kbt1** [comment]
all look good.
Thank you.
