### ISSUE TITLE
Live Version of AERAEDU is missing all students

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#32]
I logged into my Live version of the Certification Course:
http://www.aeraedu.com/#/login

now i only see test students. My live database is gone. and the SamTech tab is gone.
![image](https://user-images.githubusercontent.com/26387044/39892153-4be1d64e-5465-11e8-9acc-944a373be8df.png)
UN: Karen
Password: 5jiVsFo

Am i doing something wrong?

**Comment by kbt1** [comment]
I can login with Amandas info and everything is good.
My admin login for the live database got messed up somewhere.

**Comment by anthonypartsconnect** [comment]
@kbt1 

Hi Karen, 
Looks like there is some crosswire between admin and student accounts, we are looking into it and should have resolution by tomorrow morning. Thank your for your patience. 
-Anthony

**Comment by kbt1** [comment]
thank you!

**Comment by SagarPC** [comment]
@kbt1 : We looked into this and it's same as #30, I explain this case under #30 . We already taken action to prevent this situation in future and uploaded on stage. Please fer below reference URL for that update.

https://github.com/stellaballa/AERAEDU/issues/30#issuecomment-388046388

**Comment by kbt1** [comment]
seems to be good now.
