### ISSUE TITLE
Cylinder Head and Engine Machinist Exam Clock Issue

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#33]
Since going live with update #2. The Cylinder Head and Engine Machinist final exam clocks have been reduced down to only 1 hour for all 150 questions. This is affecting all students, not just the SAM Tech screens. It is supposed to be 3 hours for all final exams and only 1 hour for chapter test exams.

**Comment by SagarPC** [comment]
It's proper now on stage and live both. Please verify and send update to client.

![image](https://user-images.githubusercontent.com/31076567/40068976-91455e38-5887-11e8-9a99-823c2460fd37.png)

**Comment by SagarPC** [comment]
Please see my comment above. It's fixed on stage and live.

**Comment by robchar** [comment]
Looks good, thanks!

**Comment by anthonypartsconnect** [comment]
Thank you Sagar and Rob.
