### ISSUE TITLE
Completion Notifications

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#34]
Hi Guys!

I am not getting email notifications again so can you switch just the Online Certification notification emails to go to ktendering@gmail.com, this way I will get them and I dont have to search my spreadsheet and keep track of them manually.

Thank you!

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Please see Karen's comment.  Can we switch just Online Certification notification to ktendering@gmail.com.  
Thanks. - Anthony

**Comment by anthonypartsconnect** [comment]
Hi all, just an update, we have Mark (Valley Computer Solutions) looking into this on server side.  We are currently waiting on his response. Keep you posted. -Anthony

**Comment by kbt1** [comment]
thank you!

**Comment by SagarPC** [comment]
@kbt1 : updated email with "ktendering@gmail.com".

**Comment by amandagoyette** [comment]
VCS is still working on the issue. I touched base with them today.

**Comment by kbt1** [comment]
all seems to be working good. I would like to keep these notifications going to my gmail account.
thanks!
