### ISSUE TITLE
Sam Tech Online Certification

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#35]
Please clear the Sam Tech sample database as soon as possible.
I am starting with their first list of 6 students and I wanted to enter them and start getting used to the system.
I have been in touch with them and they will be sending me separate lists so since they aren't all 70 at one time, I am going to work on them.

Thank you!

**Comment by anthonypartsconnect** [comment]
Hi Karen, 

I sent a notice to Sagar and he helped to clear the list. Please see his note below:

[  I cleared all information from SAM TECH and kept only Karen's account as teacher for the SAM TECH. 
If she doesn't want her account then she can remove from by clicking on "Acc. Info" >> "View" button and "Delete Account". ]

Please let me know if that works for you.  Thanks Karen, Anthony.

**Comment by kbt1** [comment]
That is perfect, thank you very much!
