### ISSUE TITLE
Sam Tech Certification

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#36]
I added the first set of people. It went good.
2 changes:
1) can you make the date range 24 months instead of 20 months for the expiration date.
2) can you make the drop down box "Select the existing Group Name" have the most recent group i added at the top instead of the bottom.
everything else is good.

**Comment by anthonypartsconnect** [comment]
@kbt, let me confirm timing. Thank you. -- 
Anthony

**Comment by anthonypartsconnect** [comment]
@kbt1 

We are planning to have these items updated for your view Thursday. I will confirm with you Thursday morning 5/31.  Thanks  --Anthony

**Comment by kbt1** [comment]
Sounds good.
Thank you!

**Comment by kbt1** [comment]
looks good.
thank you!
