### ISSUE TITLE
Online Training Exams - Wrong Answer Box

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#37]
@SagarPC 

The wrong answer box is partially blocked by the button to retake the exam.
 See attached. 

![online training 2](https://user-images.githubusercontent.com/39140696/41611043-9264e540-73a3-11e8-8c05-7246758ea61c.JPG)

**Comment by SagarPC** [comment]
I done with the design change and uploaded on stage and production. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/41649216-a8238a76-7498-11e8-90e1-81e040226055.png)

**Comment by robchar** [comment]
Looks good, thank you!

**Comment by anthonypartsconnect** [comment]
Thank you @SagarPC!
