### ISSUE TITLE
Incorrect Answer Box - following test submission

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#38]
@SagarPC please see screenshot provided by Rob.  It looks like the question #'s are blocked in the pop-up box. Thanks -- Anthony 
![online 1 002](https://user-images.githubusercontent.com/39140696/41787000-e7c8e662-75fb-11e8-9bb8-de3dc2092b52.JPG)

**Comment by SagarPC** [comment]
We resolved this thing on live and stage both. Please re-load screen using Ctrl+F5 key and confirm our update.

Regards,

**Comment by robchar** [comment]
Everything looks good.

Thanks
Rob

**Comment by anthonypartsconnect** [comment]
Great.  Thank you Rob and Sagar.
