### ISSUE TITLE
SamTech New User Not Created Correctly - Apostrophe (') in name

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#39]
Process:
-Karen had a list of 4 users to add under the Sam Tech Tab, Group name Block032018
-She added 3 just fine. Could not add 1, but it says it has been created
-Checked 3 times that she added/created record for user it and it does not show up anywhere.
-last name of person to add was "O’Dowd", When she used "O Dowd" without the apostrophe, it worked.

It seems we need to allow apostrophe’s in names,  or else the user is not created accurately

Please see picture for reference.
1st picture: New User Creation Tab where issue using apostrophe (') occurred
2nd picture: List of users after creating 4 user, only 3 show up because of last name for fourth person
3rd picture: List of users after Karen removed apostrophe from name (successfully added)

<img width="1091" alt="screen shot 2018-08-22 at 10 38 14 am" src="https://user-images.githubusercontent.com/39140696/44480237-9b8cc800-a5f7-11e8-8965-a131f8d1fc6b.png">
<img width="1244" alt="screen shot 2018-08-22 at 10 34 47 am" src="https://user-images.githubusercontent.com/39140696/44480245-a0ea1280-a5f7-11e8-9495-76e08ee91ca4.png">
<img width="1092" alt="screen shot 2018-08-22 at 10 38 46 am" src="https://user-images.githubusercontent.com/39140696/44480262-a8112080-a5f7-11e8-87de-8f475efc387f.png">

**Comment by SagarPC** [comment]
@anthonypartsconnect : We fixed this issue and uploaded on live.

Please inform to client.

**Comment by anthonypartsconnect** [comment]
Thanks Sagar, what exactly was done to fix the issue?

**Comment by SagarPC** [comment]
@anthonypartsconnect : We changed our database query to manage Apostrophe (')  for user add/edit and upload.

**Comment by anthonypartsconnect** [comment]
Got it, Thanks.
