### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#4]
On the Dashboard of the student and teacher screen -
Chapter 7 Title should be "Engine Disassembly"
Chapter 18 title should be "Engine Installation and Break-In"

Hopefully this will also change the Select Chapter titles as well under the lesson tab as they are not capitalized either.

**Comment by SagarPC** [comment]
@robchar: We done with this update and uploaded on stage.

++++++++++++
Hopefully this will also change the Select Chapter titles as well under the lesson tab as they are not capitalized either.
++++++++++++
Yes, this change will reflect everywhere for SAM TECH.

**Comment by kbt1** [comment]
looks good
