### ISSUE TITLE
Dues Batch Edit on AERA MMS

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#40]
Under **dues processing**   can we edit a closed batch (Batch 9-4-18kt).  Client entered a dues payment for ID#812 and the "Reg Type" was input as "Membership" when it should be "Prosis Pro". 

Please change from "Membership" to "Prosis Pro".  Thank you. 
 

![image](https://user-images.githubusercontent.com/39140696/45116730-8e4bff00-b108-11e8-8696-9075efa05eae.png)

**Comment by SagarPC** [comment]
I will look into this and get back to you.

**Comment by anthonypartsconnect** [comment]
Sagar, Karen just sent an email saying these records in the batch changed from positions 1 and 2, to now 16 and 17.  #17 has to be updated.  Not sure why these would change, if you can explain that would help me.  But priority is to change #17 "reg type"
Thanks. 
![image002 3](https://user-images.githubusercontent.com/39140696/45187211-d0e30980-b1e4-11e8-96bd-b8814ea1c6e2.jpg)

**Comment by SagarPC** [comment]
@anthonypartsconnect : Inside post batch I think there is no specific order for the record.

I just have taken the proper record for the Member# 812 and updated type with "Prosis Pro" where the amount is 459.

<img width="836" alt="update_record_to_prosis_pro" src="https://user-images.githubusercontent.com/31076567/45201763-275b5100-b294-11e8-9b08-8ea205aca8dd.png">

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.  I will let client know.
