### ISSUE TITLE
Change Student's Grade 

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#41]
@SagarPC 

Please see picture below.  Can we manually change the student's score to 80% instead of 76% on the exam.  He attempted when the server was down earlier so his passing score was not recorded. 

 
![image](https://user-images.githubusercontent.com/39140696/45907658-ac268e80-bdad-11e8-8748-bedfadaa2336.png)

**Comment by SagarPC** [comment]
@anthonypartsconnect : updated score with 80%.

**Comment by anthonypartsconnect** [comment]
Thank you Sagar.
