### ISSUE TITLE
Change student's grade to show he passed Engine Machinist Exam & why did score not record

### ISSUE THREAD

**Issue by anthonypartsconnect** [stellaballa/AERAEDU#42]
@SagarPC 

Sagar, can we please **update the score for the following student** to show he completed Engine Machinist Exam.  He said he already completed but it is not reflecting on the AERA admin side.  So we should also look into **why the score was not recorded.**  

Student Name: Cody Isaak
Username: cisaak
Password: bba42252

**Comment by SagarPC** [comment]
@anthonypartsconnect: I checked with the database and it's showing 0 attempts for the Engine Machinist Exam.

Please provide me % score that I need to add for this student. I can investigate if there is an entry in the database but here I can see 0 attempts.

**Comment by SagarPC** [comment]
@anthonypartsconnect : I have updated the user with 80% score as instructed by Karen.
