### ISSUE TITLE
Online Certification - Student Completed Final - No grade posted

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#43]
the following student completed the course and all I got was this message.

![image](https://user-images.githubusercontent.com/26387044/58806006-d7b77500-85da-11e9-92f9-0e6f2bd20886.png)

2 minutes later I got an email from the student to confirm he will be sent his certificates.
"Karen, i just wanted to make sure that my test went through as completed.  i saw the sign at the end that said my certificate would be mailed to me, i just wanted to verify i was complete with the course.  
Thanks Chris Borka"

user name: cborka
password: armycb

**can you please update his record with a 90% passing grade for the final. i beleive this happened to him previously with the other exam.**

let me know when updated and I will send his certificates.
Thank you!

**Comment by SagarPC** [comment]
@kbt1 I updated his account with 90% for the final exam.

**Comment by kbt1** [comment]
Perfect, thank you!
