### ISSUE TITLE
Online Certification Program

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#45]
I added 24 students from a school (not in a Group just individually) and 2 are not showing up when I search for them but if I try to add them again, it shows their login is added already added.
I am not sure if I skipped something but I dont know why they are not showing.

here is the list that i have added, the 2 highlighted in yellow are the ones that i cant find.
if you locate them, can you fix the error.

[MNSU Online Certification Logins 24 Students.xlsx](https://github.com/stellaballa/AERAEDU/files/3864556/MNSU.Online.Certification.Logins.24.Students.xlsx)

Thank you!

**Comment by stellaballa** [comment]
@kbt1  we will take a look

**Comment by SagarPC** [comment]
I checked both users and not found any issue with the system. one is already added with a different name and another username is already exists.

1) "Nathan Meyer" added as "Nathan Miller" with username as "nmeyer". Please take appropeate action on this record.
![image](https://user-images.githubusercontent.com/31076567/69214157-2c9c7700-0b8c-11ea-86a9-7892b086a62e.png)

2) "Logan Johnson", I checked and username "ljohnson" already existed for other user. Please see the below image.
![image](https://user-images.githubusercontent.com/31076567/69214404-e85da680-0b8c-11ea-95ff-cb7afc5e1d28.png)

**Comment by kbt1** [comment]
Thank you! Got it.
