### ISSUE TITLE
Online Certification Program - Cyl Head Exam Grade Fix

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#46]
Can you please update the following account with a passing grade of 84% for the Cylinder Head Exam. I have attached an image the member sent. He passed it but the score wasnt posted.
please let me know when this has been fixed.
[Cyl Head Exam Score.pdf](https://github.com/stellaballa/AERAEDU/files/3917047/Cyl.Head.Exam.Score.pdf)

User Name: jims
Password: precise1

Thank you!

**Comment by stellaballa** [comment]
@SagarPC  please update.

**Comment by kbt1** [comment]
please let me know when this will be fixed. mbr is waiting to complete exam.
Thanks!

**Comment by SagarPC** [comment]
@kbt1 It's updated. Please ask them to do login and check.

**Comment by kbt1** [comment]
Thank you!
