### ISSUE TITLE
Taking a test

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#5]
When you click on an answer box when taking the chapter tests, you get a shadow below it.
i dont know if this can be fixed or not. You see i selected C below and there is also a blue box underneath the D answer.

![image](https://user-images.githubusercontent.com/26387044/38321264-ab28ec12-37fc-11e8-9a13-6c2729246d41.png)

**Comment by SagarPC** [comment]
@kbt1 : We fixed this one and not it's not showing shadow.

**Comment by kbt1** [comment]
looks good
