### ISSUE TITLE
Correction on the Exam Messages

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#6]
I selected **Cylinder Block Exam** but the message is about the Cylinder Head Exam

Summary
Congratulations on completing the study portion of AERA's Cylinder Head Training program. This means you have scored at least 80% on each chapter test.
Before taking the Cylinder Head exam we would like to urge you to go back and study the chapters to prepare for the exam. This exam will consist of 150 questions randomly chosen from your previous tests. Please make sure to set plenty of time aside to take this test.

You may now take the exam.

Good luck!

I select **Cylinder Head Exam** and the message is off for this.

**Summary
Congratulations on completing the study portion of AERA's Training program. This means you have scored at least 80% on each chapter test and successfully passed the Cylinder Head Exam.

Before taking the final exam we would like to urge you to go back and study the chapters to prepare for the exam. This exam will consist of 150 questions randomly chosen from your previous tests. Please make sure to set plenty of time aside to take this test.**

You may now take the exam.

Good luck!

The summary message for **Mid Term** is also off and should be reworded.

Summary
Congratulations on completing the study portion of AERA's Cylinder Head Training program. This means you have scored at least 80% on each chapter test.

Before taking the Cylinder Head exam we would like to urge you to go back and study the chapters to prepare for the exam. This exam will consist of 150 questions randomly chosen from your previous tests. Please make sure to set plenty of time aside to take this test.

You may now take the exam.

**I will have Rob look into rewording.**

**Comment by SagarPC** [comment]
@robchar : Please provide us content  once you done, so we can load same on stage.

**Comment by robchar** [comment]
@kbt1 @SagarPC @stellaballa @aharmening Please see attached the Mid Term Exam Summary, Engine Block Exam Summary, and the Cylinder Head Exam Summary to replace the summary text that is there now.
[Midterm Summary.docx](https://github.com/stellaballa/AERAEDU/files/1882149/Midterm.Summary.docx)
[Cylinder Block Exam Summary.docx](https://github.com/stellaballa/AERAEDU/files/1882150/Cylinder.Block.Exam.Summary.docx)
[Cylinder Head Exam Summary.docx](https://github.com/stellaballa/AERAEDU/files/1882151/Cylinder.Head.Exam.Summary.docx)

Thanks

**Comment by SagarPC** [comment]
@robchar : We done with the summery update as provided document.

**Comment by robchar** [comment]
Looks good, thanks.
