### ISSUE TITLE
Teacher - Student List

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#7]
Under each student there is  "view"  
the only thing under this that the teacher can do is change or add the Cylinder Head or Cylinder Block Course.  Can you add the students email as a link next to their name in case the teacher wants to email them to let the student know that they can take the next course?
Just an idea....

![image](https://user-images.githubusercontent.com/26387044/38322502-3710b824-3800-11e8-89ee-7ad801582bfa.png)

**Comment by stellaballa** [comment]
@kbt1  in the current system email address is not required. @robchar and @aharmening can you please ask the school if the teacher should communicate with student via email?

**Comment by robchar** [comment]
@kbt1 @stellaballa @aharmening I have reached out to the instructor and he has mentioned that this feature would help them greatly.

**Comment by stellaballa** [comment]
@kbt1 We will have to make student email address required. Will it work for everyone?

**Comment by kbt1** [comment]
Yes. That would be good.

**Comment by stellaballa** [comment]
@SagarPC Please make SamTech student email "required". On the teacher student dash, make the name on the first column as a link to the email address.

**Comment by SagarPC** [comment]
@stellaballa: what should be happen when Teacher click on that name as linked to the email address? or we just need to add email address as link on first name.

**Comment by stellaballa** [comment]
@SagarPC please add email address as link on the full name.

**Comment by SagarPC** [comment]
+++++++++++
Please make SamTech student email "required". 
+++++++++++
There is nothing required on create user, so we need to implement validation for that screen.

+++++++++++
On the teacher student dash, make the name on the first column as a link to the email address.
+++++++++++
We added email link on student name for the teacher login.

![image](https://user-images.githubusercontent.com/31076567/38424740-a3383e8e-39cf-11e8-8f19-be1e2f827f43.png)

**Comment by SagarPC** [comment]
Please see above for the email link.

+++++++++++
Please make SamTech student email "required".
+++++++++++
We added required field for the email only for the SAM Tech user.

**Comment by kbt1** [comment]
looks good.
