### ISSUE TITLE
Chapter 17 Title Re-name

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#8]
Please re-name chapter 17 "Preparing Performance Engines (Part A)" to
"Preparing Performance Engines (Cylinder Block)"

and chapter 17 "Preparing Performance Engines (Part B)" to
"Preparing Performance Engines (Cylinder Head)"

Thanks

**Comment by SagarPC** [comment]
done with the chapter name update on stage. 

![image](https://user-images.githubusercontent.com/31076567/38361181-2a13e9bc-38ea-11e8-94c1-383c03dd1784.png)

**Comment by kbt1** [comment]
looks good
