### ISSUE TITLE
Wrong Exam Questions (Cylinder Block)

### ISSUE THREAD

**Issue by robchar** [stellaballa/AERAEDU#9]
The test questions in Chapter 17 "Preparing Performance Engines (Part A) are not the ones that were chosen.

I have attached the correct questions.

Thanks

[Chapter 17 Cylinder Block Test QuestionsTotal 25.docx](https://github.com/stellaballa/AERAEDU/files/1877081/Chapter.17.Cylinder.Block.Test.QuestionsTotal.25.docx)

**Comment by SagarPC** [comment]
Updated newly provided question list on stage.

**Comment by robchar** [comment]
Done, thanks
